version: '3'
services:
  hope_autocomplete:
    build: .
    ports:
     - "5000:5000"
    depends_on:
      - elasticsearch
    restart: always
    environment:
      - "ELASTICSEARCH_HOSTS=['elasticsearch']"

  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:6.6.0"
    environment:
       - "discovery.type=single-node"
    restart: always